name: Continuos Integration

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs_on: ubuntu_latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm lint
