name: Continuos Integration

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.1.1
      with:
        node-version-file: '.nvmrc'
    - run: yarn install --frozen-lockfile
    - run: yarn lint

  unit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3.1.1
      with:
        node-version-file: '.nvmrc'
    - run: yarn install --frozen-lockfile
    - run: yarn test
